repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.7.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        name: Check mypy
        entry: mypy --ignore-missing-imports --namespace-packages -p tradebot
        types: [python]
        pass_filenames: false
        require_serial: true
        verbose: true
        args: [--show-error-codes]
        additional_dependencies: [mypy]

  - repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in pyproject.toml
    rev: v2.4.1
    hooks:
    - id: codespell
      additional_dependencies:
      - tomli  # for python_version < '3.11'